ARG golang_image

FROM $golang_image as builder
WORKDIR /app
ARG TARGETARCH
# Configure build with Go modules
ENV GO111MODULE=on
ENV GOPROXY=direct

# Copy modules in before the rest of the source to only expire cache on module changes:
COPY go.mod go.sum ./
RUN go mod download

COPY Makefile ./
COPY . ./
RUN make build-aws-vpc-cni && make build-linux

ENTRYPOINT ["/app/aws-vpc-cni"]
